[package]
name = "calculate_pi_rust"
version = "0.1.0"
authors = ["FelipeFTN"]
edition = "2018"

[lib]
name = "calc"
path = "./calc.rs"
crate-type = ["cdylib"]
bench = false

[dependencies]
rand = "0.8.5"
